[build]
  publish = "public"          # Directory to publish for the static frontend
  functions = "netlify/functions" # Directory where your functions are located

[functions]
  # Optional: For Node.js functions, 'esbuild' is often faster.
  # If you face issues with require/import, ensure you're using 'module' type in package.json
  # and import statements in your function file.
  node_bundler = "esbuild"
  # This tells esbuild not to bundle these modules into the lambda, assuming they are available in the Lambda environment.
  # 'node-fetch' needs to be external if you use a Node.js version in Lambda that includes it,
  # or if you prefer it not to be bundled directly for smaller function sizes.
  # For newer node-fetch, it's safer to ensure it's installed in your root package.json for the function.
  # external_node_modules = ["node-fetch"]

# Redirects are optional, but useful if you want to proxy requests cleanly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" # All /api/ requests go to functions
  status = 200